apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: flux-config
spec:
  policy:
    placementType: PickAll
    affinity:
      clusterAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          clusterSelectorTerms:
            - labelSelector: 
                matchLabels:
                  fleet.azure.com/resource-group: myfleet-rg
  resourceSelectors:
    - group: ''
      kind: Namespace
      name: cluster-config
      version: v1
  strategy:
    applyStrategy:
      allowCoOwnership: true 
