apiVersion: v1
kind: ConfigMap
metadata:
  name: myfleet-rg
  namespace: cluster-definitions
  annotations:
    kubernetes-fleet.io/envelope-configmap: "true"
data:
  group.yaml: |
    apiVersion: resources.azure.com/v1api20200601
    kind: ResourceGroup
    metadata:
      name: myfleet-rg
      namespace: cluster-definitions
      annotations:
        serviceoperator.azure.com/reconcile-policy: "skip"
    spec:
      location: eastus2